site_name: ""
site_url: https://docs.khipu.utec.edu.pe
site_description: Documentación de Khipu
site_author: Roosevelt Ubaldo Chavez
# repo_url: https://github.com/khipu-utec/khipu-utec.github.io
# repo_name: khipu-utec/khipu-utec.github.io
nav:
  - Home: index.md
  - Sobre Khipu:
    - info/index.md
    - Infraestructura: info/infraestructura.md
    - Políticas de uso: info/politicas-de-uso.md
    - Tipos de cuentas: info/tipos-de-cuentas.md
  - Primeros pasos:
    - primeros-pasos/index.md
    - Solicitar acceso: primeros-pasos/solicitar-acceso.md
    - Acceder a Khipu: primeros-pasos/acceder-a-khipu.md
    - Cambiar contraseña: primeros-pasos/cambiar-contrasena.md
    - Configurar llaves SSH: primeros-pasos/configurar-llaves-ssh.md
    - Transferir archivos: primeros-pasos/transferir-archivos.md
    - Siguientes pasos: primeros-pasos/siguientes-pasos.md
  - Guía de Usuario:  
    - Enviar jobs: 
      - guia-de-usuario/enviar-jobs/index.md
      - Comandos Básicos: guia-de-usuario/enviar-jobs/comandos-basicos.md
      - Creación de Script: guia-de-usuario/enviar-jobs/creacion-script.md
      - Parámetros de Slurm: guia-de-usuario/enviar-jobs/parametros.md
      - Particiones: guia-de-usuario/enviar-jobs/particiones.md
      - Monitorear jobs: guia-de-usuario/enviar-jobs/monitorear.md
    - Software:
      - guia-de-usuario/software/index.md
      - Uso de software: guia-de-usuario/software/uso.md
      - Software disponible: guia-de-usuario/software/lista.md
      - Instalación: guia-de-usuario/software/instalacion.md
    - Ejemplos:
      - Introductorios: guia-de-usuario/ejemplos/introductorios.md
      - MPI/OpenMP: guia-de-usuario/ejemplos/mpi-openmp.md
      - Python: guia-de-usuario/ejemplos/python.md
      - Miniconda: guia-de-usuario/ejemplos/miniconda.md
  - Tutoriales: 
    - Reinicio de Jobs: tutoriales/reinicio-job-pytorch.md
    - Apptainer: tutoriales/apptainer.md
    - Jupyter [pip]: tutoriales/jupyter-pip.md
    - Jupyter [conda]: tutoriales/jupyter-conda.md
  - Anuncios:
    - anuncios/index.md
  - Soporte: 
    - soporte/index.md
    - ¿Cómo crear un ticket de soporte?: soporte/mesa-de-ayuda.md
theme:
  name: material
  custom_dir: mkdocs_khipu
  logo: assets/logos/logo.webp
  favicon: assets/logos/favicon-16x16.png
  language: es
  palette:
    primary: white
    scheme: khipu
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    tag:
      python: fontawesome/brands/python
  # behave like single page app
  # font:
  #   text: Popins
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune # only load which is visible
    - navigation.indexes
    - toc.follow
    - navigation.top # back to top
    - search.suggest
    - search.highlight
    - search.share
    - announce.dismiss

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage
  social:
    - icon: fontawesome/solid/globe
      link: https://web.khipu.utec.edu.pe/
      name: Página Web
    - icon: fontawesome/brands/github 
      link: https://github.com/khipu-utec
      name: Organización en GitHub
    - icon: fontawesome/solid/envelope
      link: mailto:khipu@utec.edu.pe
      name: Correo electrónico
    - icon: fontawesome/solid/headset
      link: https://servicedesk.utec.edu.pe/
      name: Soporte

  tags:
    Python: python

plugins:
  - search
  - meta # meta for blog
  - blog:
      blog_dir: anuncios
  - tags
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: khipu-utec/khipu-utec.github.io
      branch: main
  - encryptcontent:
      password_file: 'passwords.yml'
  # - social: # revisar luego
  #     cards_layout_options:
  #       font_family: Noto Sans SC
markdown_extensions:
  - pymdownx.blocks.caption
  - abbr
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - admonition  # callout
  - pymdownx.details
  - pymdownx.superfences  # tabs
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list # add html objects
  - md_in_html # md inside html
  - footnotes
  - tables # create tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic # highlight
  - pymdownx.caret # sub and supe script
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys # key rendering
  - pymdownx.snippets

# to load abbreviations as is outside docs/
watch:
  - includes

extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2025 Khipu - <a href="#__consent">Change cookie settings</a>